version: "3.9"  # optional since v1.27.0
services:
  grafana:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:~/data
    networks:
      - magic-net    
networks:
  default:
    name: magic-net
    external: true