version: "3.9"
services:
  prometheus:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - .:~/data
    networks:
      - magic-net    
networks:
  default:
    name: magic-net
    external: true