version: "3.9"
services:
  magic-ball:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:~/data
    networks:
      - magic-net    
networks:
  default:
    name: magic-net
    external: true